// <auto-generated />
namespace SHBC_SNN.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TitleNulls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TitleNulls));
        
        string IMigrationMetadata.Id
        {
            get { return "201503130956098_TitleNulls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
