// <auto-generated />
namespace SHBC_SNN.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _20150311 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20150311));
        
        string IMigrationMetadata.Id
        {
            get { return "201503111616218_2015-03-11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
