// <auto-generated />
namespace SHBC_SNN.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ContactTitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContactTitle));
        
        string IMigrationMetadata.Id
        {
            get { return "201503131032013_ContactTitle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
