// <auto-generated />
namespace SHBC_SNN.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Contact_Enum_addition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Contact_Enum_addition));
        
        string IMigrationMetadata.Id
        {
            get { return "201503121435142_Contact_Enum_addition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
