// <auto-generated />
namespace SHBC_SNN.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ModifiedModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifiedModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201507211417147_ModifiedModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
